apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rhbk-demo.yaml
  # spiffe-system.yaml removed - Operator manages resources in zero-trust-workload-identity-manager namespace
