apiVersion: v1
kind: Namespace
metadata:
  name: rhbk-demo
  labels:
    app.kubernetes.io/name: rhbk-demo
    app.kubernetes.io/part-of: rhbk-spiffe
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
