apiVersion: operator.openshift.io/v1alpha1
kind: ZeroTrustWorkloadIdentityManager
metadata:
  name: cluster
  namespace: zero-trust-workload-identity-manager
spec:
  clusterName: cluster-hb456.hb456.sandbox3244.opentlc.com
