apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ztwim/namespace.yaml
  - ztwim/operatorgroup.yaml
  - ztwim/subscription.yaml
  - rhbk/operatorgroup.yaml
  - rhbk/subscription.yaml
  - argocd-clusterrole-binding.yaml
