apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 10-operators
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/kamorisan/spiffe-rhbk.git
    targetRevision: main
    path: platform/operators
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
