apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 20-spire
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/kamorisan/spiffe-rhbk.git
    targetRevision: main
    path: spire/overlays/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - SkipDryRunOnMissingResource=true
  ignoreDifferences:
  - group: operator.openshift.io
    kind: SpireServer
    name: cluster
    jqPathExpressions:
    - .spec
    - .status
  - group: operator.openshift.io
    kind: SpireAgent
    name: cluster
    jqPathExpressions:
    - .spec
    - .status
