apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 20-spire
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/kamorisan/spiffe-rhbk.git
    targetRevision: main
    path: spire/overlays/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - SkipDryRunOnMissingResource=true
  ignoreDifferences:
  - group: operator.openshift.io
    kind: SpireServer
    jsonPointers:
    - /status
    - /metadata/managedFields
  - group: operator.openshift.io
    kind: SpireAgent
    jsonPointers:
    - /status
    - /metadata/managedFields
  - group: operator.openshift.io
    kind: SpireServer
    managedFieldsManagers:
    - kube-controller-manager
  - group: operator.openshift.io
    kind: SpireAgent
    managedFieldsManagers:
    - kube-controller-manager
