apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 30-rhbk
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  source:
    repoURL: https://github.com/kamorisan/spiffe-rhbk.git
    targetRevision: main
    path: rhbk/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: rhbk-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - SkipDryRunOnMissingResource=true
