apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 50-test-workloads
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: default
  source:
    repoURL: https://github.com/kamorisan/spiffe-rhbk.git
    targetRevision: main
    path: test-workloads/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: rhbk-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
