apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/ztwim-patch.yaml
  - path: patches/spireserver-patch.yaml
  - path: patches/spireoidcdiscoveryprovider-patch.yaml
